<?php
// User-facing password reset page
// Usage: reset_password.php?token=... (token generated by admin)
if (session_status() == PHP_SESSION_NONE) session_start();

require_once __DIR__ . '/config/database.php';

$message = '';
$messageType = '';

try {
    $database = new Database();
    $db = $database->getConnection();
} catch (Exception $e) {
    $message = 'Database unavailable: ' . htmlspecialchars($e->getMessage());
    $messageType = 'error';
    $db = null;
}

$token = $_GET['token'] ?? $_POST['token'] ?? '';
$token = trim($token);

// Helper: fetch token row
function fetchTokenRow($db, $token) {
    $stmt = $db->prepare('SELECT * FROM password_resets WHERE token = :token LIMIT 1');
    $stmt->bindParam(':token', $token);
    $stmt->execute();
    return $stmt->fetch(PDO::FETCH_ASSOC);
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // Handle password update
    $new = $_POST['new_password'] ?? '';
    $confirm = $_POST['confirm_password'] ?? '';
    $token = $_POST['token'] ?? '';

    if (!$db) {
        $message = 'Database connection not available.';
        $messageType = 'error';
    } elseif (!$token) {
        $message = 'Missing token.';
        $messageType = 'error';
    } elseif (strlen($new) < 6) {
        $message = 'Password must be at least 6 characters long.';
        $messageType = 'warning';
    } elseif ($new !== $confirm) {
        $message = 'Password and confirmation do not match.';
        $messageType = 'warning';
    } else {
        $row = fetchTokenRow($db, $token);
        if (!$row) {
            $message = 'Invalid or already-used token.';
            $messageType = 'error';
        } else {
            $expires = strtotime($row['expires_at']);
            if ($expires < time()) {
                // delete expired token
                $del = $db->prepare('DELETE FROM password_resets WHERE id = :id');
                $del->bindParam(':id', $row['id']);
                $del->execute();
                $message = 'This reset link has expired. Please ask the administrator to generate a new one.';
                $messageType = 'error';
            } else {
                // Update user's password
                $userId = intval($row['user_id']);
                $hashed = password_hash($new, PASSWORD_DEFAULT);
                $upd = $db->prepare('UPDATE users SET password = :pwd WHERE id = :uid');
                $upd->bindParam(':pwd', $hashed);
                $upd->bindParam(':uid', $userId);
                if ($upd->execute()) {
                    // Invalidate all tokens for this user
                    $del = $db->prepare('DELETE FROM password_resets WHERE user_id = :uid');
                    $del->bindParam(':uid', $userId);
                    $del->execute();

                    $message = 'Password updated successfully. You can now <a href="login.php">log in</a> with your new password.';
                    $messageType = 'success';
                } else {
                    $message = 'Failed to update password. Please contact admin.';
                    $messageType = 'error';
                }
            }
        }
    }

} else {
    // GET - validate token presence and show form
    if (!$db) {
        // already handled
    } elseif (!$token) {
        $message = 'No reset token provided.';
        $messageType = 'error';
    } else {
        $row = fetchTokenRow($db, $token);
        if (!$row) {
            $message = 'Invalid or expired reset link.';
            $messageType = 'error';
        } else {
            if (strtotime($row['expires_at']) < time()) {
                $message = 'This reset link has expired. Please ask the administrator for a new link.';
                $messageType = 'error';
            }
        }
    }
}

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Reset Password</title>
    <link rel="stylesheet" href="assets/css/style.css">
</head>
<body>
    <?php include __DIR__ . '/includes/header.php'; ?>
    <?php include __DIR__ . '/includes/navigation.php'; ?>

    <div class="main-container">
        <h1 class="page-title">Reset Your Password</h1>

        <?php if ($message): ?>
            <div class="alert alert-<?php echo htmlspecialchars($messageType); ?>"><?php echo $message; ?></div>
        <?php endif; ?>

        <?php if (($messageType !== 'success') && (!isset($row) || $row)): ?>
            <?php if (isset($row) && $row && strtotime($row['expires_at']) >= time()): ?>
            <div class="content-card" style="max-width:520px;margin:0 auto;">
                <form method="POST" id="resetForm">
                    <input type="hidden" name="token" value="<?php echo htmlspecialchars($token); ?>">

                    <div class="form-group">
                        <label for="new_password" class="form-label">New Password *</label>
                        <input type="password" id="new_password" name="new_password" class="form-input" required minlength="6" placeholder="Choose a strong password">
                    </div>

                    <div class="form-group">
                        <label for="confirm_password" class="form-label">Confirm Password *</label>
                        <input type="password" id="confirm_password" name="confirm_password" class="form-input" required minlength="6" placeholder="Repeat the password">
                    </div>

                    <button type="submit" class="btn btn-primary">Set New Password</button>
                </form>
            </div>
            <?php else: ?>
                <!-- If no valid row, nothing to show -->
            <?php endif; ?>
        <?php endif; ?>

    </div>

    <script src="assets/js/script.js"></script>
    <script>
        // basic client-side validation
        document.addEventListener('DOMContentLoaded', function(){
            const form = document.getElementById('resetForm');
            if (!form) return;
            form.addEventListener('submit', function(e){
                const a = document.getElementById('new_password');
                const b = document.getElementById('confirm_password');
                if (a.value.length < 6) {
                    e.preventDefault(); showNotification('Password must be at least 6 characters', 'warning'); return;
                }
                if (a.value !== b.value) {
                    e.preventDefault(); showNotification('Passwords do not match', 'error'); return;
                }
            });
        });
    </script>
</body>
</html>
